### ISSUE TITLE
执行init-mysql-database.sh时找不到fd_service.groovy

### ISSUE THREAD

**Issue by xuxigang** [choerodon/base-service#3]
2020-01-21 17:23:10.349 ERROR 14172 --- [           main] liquibase                                : script/db/fd_service.groovy: script/db/fd_service.groovy::2019
-10-26-fd-route-add-column::zongw.lee@gmail.com: Change Set script/db/fd_service.groovy::2019-10-26-fd-route-add-column::zongw.lee@gmail.com failed.  Error: Table
'base_service.fd_route' doesn't exist [Failed SQL: ALTER TABLE base_service.fd_route ADD STRIP_PREFIX INT UNSIGNED NULL COMMENT '是否去前缀' , ADD SENSITIVE_HEADER
S TEXT NULL COMMENT '敏感头部列表' , ADD ROUTE_ID VARCHAR(64) NOT NULL COMMENT '路由ID']
2020-01-21 17:23:10.365  INFO 14172 --- [           main] liquibase                                : script/db/fd_service.groovy::2019-10-26-fd-route-add-column::z
ongw.lee@gmail.com: Successfully released change log lock
2020-01-21 17:23:10.372 ERROR 14172 --- [           main] i.choerodon.liquibase.LiquibaseExecutor  : 数据库初始化任务失败, message: Migration failed for change set
 script/db/fd_service.groovy::2019-10-26-fd-route-add-column::zongw.lee@gmail.com:
     Reason: liquibase.exception.DatabaseException: Table 'base_service.fd_route' doesn't exist [Failed SQL: ALTER TABLE base_service.fd_route ADD STRIP_PREFIX INT
 UNSIGNED NULL COMMENT '是否去前缀' , ADD SENSITIVE_HEADERS TEXT NULL COMMENT '敏感头部列表' , ADD ROUTE_ID VARCHAR(64) NOT NULL COMMENT '路由ID'], exception:

liquibase.exception.MigrationFailedException: Migration failed for change set script/db/fd_service.groovy::2019-10-26-fd-route-add-column::zongw.lee@gmail.com:
     Reason: liquibase.exception.DatabaseException: Table 'base_service.fd_route' doesn't exist [Failed SQL: ALTER TABLE base_service.fd_route ADD STRIP_PREFIX INT
 UNSIGNED NULL COMMENT '是否去前缀' , ADD SENSITIVE_HEADERS TEXT NULL COMMENT '敏感头部列表' , ADD ROUTE_ID VARCHAR(64) NOT NULL COMMENT '路由ID']
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.Liquibase.update(Liquibase.java:214) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.Liquibase.update(Liquibase.java:188) ~[liquibase-core-3.5.5.jar!/:na]
        at io.choerodon.liquibase.LiquibaseExecutor.load(LiquibaseExecutor.java:276) ~[choerodon-liquibase-0.11.0.RELEASE.jar!/:0.11.0.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.runToDb(LiquibaseExecutor.java:193) ~[choerodon-liquibase-0.11.0.RELEASE.jar!/:0.11.0.RELEASE]
        at io.choerodon.liquibase.LiquibaseExecutor.execute(LiquibaseExecutor.java:97) ~[choerodon-liquibase-0.11.0.RELEASE.jar!/:0.11.0.RELEASE]
        at io.choerodon.liquibase.StartupRunner.run(StartupRunner.java:28) [classes!/:0.11.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:792) [spring-boot-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776) [spring-boot-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.0.6.RELEASE.jar!/:2.0.6.RELEASE]
        at io.choerodon.liquibase.LiquibaseTools.main(LiquibaseTools.java:18) [classes!/:0.11.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [choerodon-tool-liquibase-0.11.0.RELEASE.jar:0.11.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [choerodon-tool-liquibase-0.11.0.RELEASE.jar:0.11.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [choerodon-tool-liquibase-0.11.0.RELEASE.jar:0.11.0.RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [choerodon-tool-liquibase-0.11.0.RELEASE.jar:0.11.0.RELEASE]
Caused by: liquibase.exception.DatabaseException: Table 'base_service.fd_route' doesn't exist [Failed SQL: ALTER TABLE base_service.fd_route ADD STRIP_PREFIX INT U
NSIGNED NULL COMMENT '是否去前缀' , ADD SENSITIVE_HEADERS TEXT NULL COMMENT '敏感头部列表' , ADD ROUTE_ID VARCHAR(64) NOT NULL COMMENT '路由ID']
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259) ~[liquibase-core-3.5.5.jar!/:na]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582) ~[liquibase-core-3.5.5.jar!/:na]
        ... 21 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'base_service.fd_route' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_45]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[mysql-connector-java-5.1.47.jar!/:5.1.47]
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-2.7.9.jar!/:na]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307) ~[liquibase-core-3.5.5.jar!/:na]
        ... 26 common frames omitted

**Comment by hudayee** [comment]
我也遇到该问题，将`my.cnf`中 `[mysqld]` 设置 `lower_case_table_names=1`
